name: Update DNS providers

on:
  workflow_dispatch:
    
  schedule:
    - cron:  '0 7 * * 3'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Update DNS providers
        run: |
          ./update-providers.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6bb739433928fbc2bdc635d41105e124d0dce021
        with:
          title: Update DNS Providers
          body: |
            Sync DNS Providers with go-acme/lego/providers/dns
          labels: dns, automated pr
          commit-message: Update DNS Providers
          branch: auto-update-dns-providers
          delete-branch: true
          
          
