name: Update DNS providers

on:
  workflow_dispatch:
    
  schedule:
    - cron:  '0 7 * * 3'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Update DNS providers
        run: |
          ./update-providers.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update DNS Providers
          labels: dns, automated pr
